# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param StringVector strings
#' @export
read_header <- function(strings) {
    .Call(`_myPackage_read_header`, strings)
}

